### PR TITLE
Upgrade j-ftp to 1.60 but strip redundant log4j, commons-logging, commons-codec

### PR DESCRIPTION
**Pull request by mkortkamp**
There were redundant versions of these libraries bundled inside the j-ftp 
release jar. Therefore during development log4j was used directly instead of 
the slf4j bridge for log4j. Maybe this was compensated by the build script 
when copying it all together or maybe it created a wild non-deterministic
version mix. 
Current j-ftp version was downloaded from the projects sourceforge page:
http://downloads.sourceforge.net/project/j-ftp/jftp/1.60/j-ftp-1.60.tar.gz
Just wanted to have slf4j used instead of log4j complaining about missing
configuration - but seemed like a good opportunity to upgrade to the 
latest version ...according to the changelog this should also solve some
problems with large files.

### CODE REVIEW

**Comment by mkortkamp** [comment]
see also mkortkamp/trolcommander#21

**Comment by mkortkamp** [comment]
wait - not ready yet ...sorry

**Comment by mkortkamp** [comment]
@trol73 
just got a lot of errors after refreshing my eclipse after my rebase on your latest develop head.
Any reason why you commented out the `com.sshtools.j2ssh.sftp.*` import in `SFTPFile` or just by mistake?

**Comment by trol73** [comment]
Sorry, looks like I broke the build. I worked on the migration to the latest version `com.sshtools.j2ssh` .
So now we have the latest version of FTP and SFTP libraries.
Thanks

**Pull request merged**
